/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    BetterAuthSecret: {
      type: 'sst.sst.Secret';
      value: string;
    };
    Bucket: {
      name: string;
      type: 'sst.aws.Bucket';
    };
    Database: {
      database: string;
      host: string;
      password: string;
      port: number;
      type: 'sst.aws.Postgres';
      username: string;
    };
    DatabaseMigrator: {
      name: string;
      type: 'sst.aws.Function';
    };
    Email: {
      configSet: string;
      sender: string;
      type: 'sst.aws.Email';
    };
    GoogleAuthClientId: {
      type: 'sst.sst.Secret';
      value: string;
    };
    GoogleAuthClientSecret: {
      type: 'sst.sst.Secret';
      value: string;
    };
    Redis: {
      host: string;
      password: string;
      port: number;
      type: 'sst.aws.Redis';
      username: string;
    };
    Vpc: {
      bastion: string;
      type: 'sst.aws.Vpc';
    };
    Web: {
      type: 'sst.aws.TanstackStart';
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
