# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class Bucket:
        name: str
        type: str
    class Database:
        database: str
        host: str
        password: str
        port: float
        type: str
        username: str
    class DatabaseMigrator:
        name: str
        type: str
    class Frontend:
        type: str
        url: str
    class GoogleGenAIKey:
        type: str
        value: str
    class Vpc:
        bastion: str
        type: str
    class ZeroAuthSecret:
        type: str
        value: str

